[build]
builder = "NIXPACKS"
installCommand = "npm ci"
buildCommand = "npm run build --workspace=shared && npm run build --workspace=server"

[deploy]
startCommand = "npm run start --workspace=server"
healthcheckPath = "/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
